import PostItem from '@/components/client/posts/PostItem';
import PostItemTrending from '@/components/client/posts/PostItemTrending';
import ClientLayout from '@/layout/ClientLayout';
import Head from 'next/head';

export default function Home() {
    return (
        <>
            <Head>
                <title>Cosmos Code</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/images/logo.png" />
            </Head>

            <ClientLayout>
                <section>
                    <div className="bg-cover bg-center h-60 sm:h-96" style={{ backgroundImage: 'url("https://source.unsplash.com/random")' }}>
                        <div className="container mx-auto items-center">
                            <div className="text-white font-bold text-xl text-center">Welcome to my website</div>
                        </div>
                    </div>

                </section>
                <section className="px-4 py-6 border-b">
                    <div className="container mx-auto max-w-screen-xl">
                        <h2 className="text-2xl font-bold mb-4">Featured Articles</h2>
                        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:grid-cols-3">
                            <PostItemTrending />
                            <PostItemTrending />
                            <PostItemTrending />
                            <PostItemTrending />
                            <PostItemTrending />
                            <PostItemTrending />
                        </div>
                    </div>
                </section>
                <section className="px-4 py-6">
                    <div className="container mx-auto max-w-screen-xl">
                        <div className="grid grid-cols-1 gap-4 sm:grid-cols-6">
                            <section className="col-span-1 sm:col-span-4">
                                <div className="grid grid-cols-1 gap-4">
                                    <PostItem />
                                    <PostItem />
                                    <PostItem />
                                    <PostItem />
                                    <PostItem />
                                </div>
                            </section>
                            <aside className="col-span-1 sm:col-span-2">
                                <div className="sticky top-20">
                                    <div className="p-2 border-b">
                                        <a href="#" className="border border-gray-500 text-gray-500 py-2 px-4 inline-flex items-center hover:bg-gray-50 m-1">
                                            <span>Programing</span>
                                        </a>
                                        <a href="#" className="border border-gray-500 text-gray-500 py-2 px-4 inline-flex items-center hover:bg-gray-50 m-1">
                                            <span>Writing</span>
                                        </a>
                                        <a href="#" className="border border-gray-500 text-gray-500 py-2 px-4 inline-flex items-center hover:bg-gray-50 m-1">
                                            <span>Javascript</span>
                                        </a>
                                        <a href="#" className="border border-gray-500 text-gray-500 py-2 px-4 inline-flex items-center hover:bg-gray-50 m-1">
                                            <span>English</span>
                                        </a>
                                        <a href="#" className="border border-gray-500 text-gray-500 py-2 px-4 inline-flex items-center hover:bg-gray-50 m-1">
                                            <span>Nextjs</span>
                                        </a>
                                    </div>
                                    <div className="p-2">
                                        <a href="" className="text-gray-500 py-2 px-4 my-1 inline-flex items-center">
                                            Help
                                        </a>
                                        <a href="" className="text-gray-500 py-2 px-4 my-1 inline-flex items-center">
                                            About
                                        </a>
                                        <a href="" className="text-gray-500 py-2 px-4 my-1 inline-flex items-center">
                                            Blog
                                        </a>
                                        <a href="" className="text-gray-500 py-2 px-4 my-1 inline-flex items-center">
                                            Help
                                        </a>
                                        <a href="" className="text-gray-500 py-2 px-4 my-1 inline-flex items-center">
                                            Privacy
                                        </a>
                                        <a href="" className="text-gray-500 py-2 px-4 my-1 inline-flex items-center">
                                            Terms
                                        </a>
                                    </div>
                                </div>
                            </aside>
                        </div>
                    </div>
                </section>
            </ClientLayout>
        </>
    )
}
